### ISSUE TITLE
请问一直正在搜索代理中，怎么办？

### ISSUE THREAD

**Issue by mxf11** [sharmajv/vpn#26]
十多个小时了，目前搜到了20多个…应该不正常。怎么解决呢？谢谢
![Screenshot_2022-12-16-14-56-08-108_org vpndigger](https://user-images.githubusercontent.com/120708021/208043646-a7cdb7d5-eab9-4b15-ad5a-d103ce5035e4.jpg)

**Comment by KevinDeng233** [comment]
The same.
